'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")>  _
Partial Friend NotInheritable Class FFFOperatorSettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As FFFOperatorSettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New FFFOperatorSettings()),FFFOperatorSettings)
    
    Public Shared ReadOnly Property [Default]() As FFFOperatorSettings
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
    Public Property StartUpNumberOfFFFContestants() As String
        Get
            Return CType(Me("StartUpNumberOfFFFContestants"),String)
        End Get
        Set
            Me("StartUpNumberOfFFFContestants") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
    Public Property ClockDecimalPlaces() As String
        Get
            Return CType(Me("ClockDecimalPlaces"),String)
        End Get
        Set
            Me("ClockDecimalPlaces") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
    Public Property DurationOfFFFGameTime() As String
        Get
            Return CType(Me("DurationOfFFFGameTime"),String)
        End Get
        Set
            Me("DurationOfFFFGameTime") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Setting() As String
        Get
            Return CType(Me("Setting"),String)
        End Get
        Set
            Me("Setting") = value
        End Set
    End Property
End Class
