'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")>  _
Partial Friend NotInheritable Class GameConfiguration
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As GameConfiguration = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New GameConfiguration()),GameConfiguration)
    
    Public Shared ReadOnly Property [Default]() As GameConfiguration
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C:\ShowControl")>  _
    Public Property DefaultGameConfigurationPath() As String
        Get
            Return CType(Me("DefaultGameConfigurationPath"),String)
        End Get
        Set
            Me("DefaultGameConfigurationPath") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("C:\ShowControl")>  _
    Public Property DefaultContestantsOnTheShowPath() As String
        Get
            Return CType(Me("DefaultContestantsOnTheShowPath"),String)
        End Get
        Set
            Me("DefaultContestantsOnTheShowPath") = value
        End Set
    End Property
End Class
